### ISSUE TITLE
Error using with Phaser 3.16.2

### ISSUE THREAD

**Issue by achojoao** [jsfehler/phaser-ui-tools#25]
Thanks for the library, it's amazing. Great job!

Just adding the file in the index.html and reloading I get this error:

phaser-ui-tools.js:41 Uncaught TypeError: Super expression must either be null or a function, not undefined
    at inherits (phaser-ui-tools.js:41)
    at phaser-ui-tools.js:77
    at phaser-ui-tools.js:124
    at phaser-ui-tools.js:4
    at phaser-ui-tools.js:5
inherits @ phaser-ui-tools.js:41
(anonymous) @ phaser-ui-tools.js:77
(anonymous) @ phaser-ui-tools.js:124
(anonymous) @ phaser-ui-tools.js:4
(anonymous) @ phaser-ui-tools.js:5
phaser.min.js:1      My Game / Phaser v3.16.2 (WebGL | Web Audio)

**Comment by jsfehler** [comment]
I haven't done any testing in Phaser 3. Is it specifically 3.16.2 that's failing, or even previous versions?

From a brief look at the documentation, Phaser.Group is now Phaser.GameObjects.Group. At the very least that's going to break everything.

Assuming Group works the same way, creating an alias to support both isn't difficult. However, Phaser.Signal is used in a few places, and that doesn't exist at all in Phaser 3. It's been replaced with Phaser.Events.EventEmitter, which uses the EventEmitter3 library. Off the top of my head, the safest way to support Phaser CE and Phaser 3 would be to import EventEmitter3 and replace Phaser.Signal with that.

**Comment by achojoao** [comment]
Ok, I though the library was ready for Phaser 3 too. My falut. Thanks!
