### ISSUE TITLE
Road to Phaser 3 compatibility

### ISSUE THREAD

**Issue by jsfehler** [jsfehler/phaser-ui-tools#28]
The ambition is to support Phaser CE and Phaser 3 with the same library, without added configuration.

**Known Knowns:**
- [x] Use eventemitter3 instead of CE's Phaser.Signal or Phaser 3's implementation of eventemitter3
- [x] Don't extend Phaser objects directly, use an intermediary (ie: Handle Phaser.Group vs Phaser.GameObjects.Group)
- [x] Phaser 3: Build a shim for CE's Sprite's sendToBack() and alignIn() methods. ui-tools will still call the old methods.
- [x] Handle Phaser CE vs Phaser 3 Graphics object

**Known Unknowns:**
- [x] Difference between Phaser CE tweens and Phaser 3 tweens

**Unknown Unknowns:**

Still unknown, unfortunately...

**Phaser 3 Tool Status**
- [x] TextButton
- [x] TextSprite
- [x] Column
- [x] Row
- [x] Viewport
- [x] Scrollbar
- [x] ValueBar
- [x] QuantityBar
- [x] Wheel3D

**Comment by dasheck0** [comment]
Hey. This seems interesting and very promising. Is this still supported? How is the progress towards Phaser 3. Also do you plan to publish it to npmjs? This would be appreciated, since modern Phaser 3 game development almost always includes npm packages.

**Comment by jsfehler** [comment]
The groundwork has been laid on the master branch. The Phaser logic has been abstracted away from the UI Tools logic. IIRC Nothing should crash anymore if you try to load this library in Phaser 3. However, aside from QuantityBar everything is screwy in Phaser 3.

Before I do a release with partial Phaser 3 support, I need to finish Phaser 3 versions of the unit tests.

Beyond a partial compatibility release, I don't have time to do serious work on this project. If anyone is interested in contributing, I'll gladly look at PRs.

In terms of when I can finish on my own, you're looking at November/December at the earliest.

**Comment by jsfehler** [comment]
Everything works on Phaser 3. Once testing is done, version 1.0 will be released.
